//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayOfWeekConsoleClient.BGDayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BGDayService.IDayOfWeekInBulgarian")]
    public interface IDayOfWeekInBulgarian {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeekInBulgarian/GetDayOfWeekInBulgarian", ReplyAction="http://tempuri.org/IDayOfWeekInBulgarian/GetDayOfWeekInBulgarianResponse")]
        string GetDayOfWeekInBulgarian(System.DateTime value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeekInBulgarian/GetDayOfWeekInBulgarian", ReplyAction="http://tempuri.org/IDayOfWeekInBulgarian/GetDayOfWeekInBulgarianResponse")]
        System.Threading.Tasks.Task<string> GetDayOfWeekInBulgarianAsync(System.DateTime value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDayOfWeekInBulgarianChannel : DayOfWeekConsoleClient.BGDayService.IDayOfWeekInBulgarian, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DayOfWeekInBulgarianClient : System.ServiceModel.ClientBase<DayOfWeekConsoleClient.BGDayService.IDayOfWeekInBulgarian>, DayOfWeekConsoleClient.BGDayService.IDayOfWeekInBulgarian {
        
        public DayOfWeekInBulgarianClient() {
        }
        
        public DayOfWeekInBulgarianClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DayOfWeekInBulgarianClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfWeekInBulgarianClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfWeekInBulgarianClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayOfWeekInBulgarian(System.DateTime value) {
            return base.Channel.GetDayOfWeekInBulgarian(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDayOfWeekInBulgarianAsync(System.DateTime value) {
            return base.Channel.GetDayOfWeekInBulgarianAsync(value);
        }
    }
}
